language: c
git:
  submodules: true
env:
  global:
    - secure: "YEhcMuHvycqdfQZhCJhDz9aw56tmvvfr+k/1hiGsIQx7zyZbLR03wUT4EUQAKdG57lOGHZwUdb4koW+OAG3ZVD7rWlw2UOw4G7BiWbQeVXO8isQiFd3CtIRvqbeEzDsu/AQGa8MSb9zoEbFRvV7MDd9TuKbiwVDoPyKGI6qZioA="
matrix:
  include:
  - os: linux
    sudo: required
    dist: focal
    compiler: g++
    env:
      - NODE_VERSION=18
  - os: linux
    sudo: required
    dist: focal
    compiler: g++
    env:
      - NODE_VERSION=20
  # - os: osx
  #   osx_image: xcode13.4
  #   compiler: clang
  #   env:
  #     - NODE_VERSION=14
  # - os: osx
  #   osx_image: xcode13.4
  #   compiler: clang
  #   env:
  #     - NODE_VERSION=16
  # - os: osx
  #   osx_image: xcode13.4
  #   compiler: clang
  #   env:
  #     - NODE_VERSION=18
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - xutils-dev
    - libxi-dev
    - libxxf86vm-dev
    - x11proto-xf86vidmode-dev
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
    - musl-dev
    - libgl1-mesa-dev
before_install:
- ./scripts/before_install.sh
install:
- ./scripts/install.sh
before_script:
- ulimit -c unlimited -S
- ulimit -a
script:
- ./scripts/test.sh
after_success:
- ./scripts/after_success.sh
