# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: ci
on:
  push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install -y build-essential libgl1-mesa-dri libglapi-mesa
                                     libglew-dev libglu1-mesa-dev libosmesa6
                                     libxi-dev mesa-utils pkg-config
      - run: npm ci
      - run: npm run build --if-present
      - if: startsWith(matrix.os, 'ubuntu')
        run: xvfb-run npm test
      - if: "!startsWith(matrix.os, 'ubuntu')"
        run: npm test
